//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ozyer.Areas.admin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipationSectorWorks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParticipationSectorWorks()
        {
            this.ParticipationSectorWorkFile = new HashSet<ParticipationSectorWorkFile>();
            this.ParticipationSectorWorkFile1 = new HashSet<ParticipationSectorWorkFile>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParticipationId { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParticipationSectorCategoryId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsPassive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Participations Participations { get; set; }
        public virtual ParticipationSectorCategories ParticipationSectorCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipationSectorWorkFile> ParticipationSectorWorkFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipationSectorWorkFile> ParticipationSectorWorkFile1 { get; set; }
    }
}
