//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ozyer.Areas.admin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipationSectorCategories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParticipationSectorCategories()
        {
            this.ParticipationSectorWorks = new HashSet<ParticipationSectorWorks>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParticipationId { get; set; }
        public Nullable<int> SectorId { get; set; }
        public string Name { get; set; }
        public string Logo { get; set; }
        public string FriendlyUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipationSectorWorks> ParticipationSectorWorks { get; set; }
    }
}
