//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ozyer.Areas.admin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipationSectorWorkFile
    {
        public int Id { get; set; }
        public Nullable<int> ParticipationSectorWorkId { get; set; }
        public string Path { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual ParticipationSectorWorks ParticipationSectorWorks { get; set; }
        public virtual ParticipationSectorWorks ParticipationSectorWorks1 { get; set; }
    }
}
