//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ozyer.Areas.admin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Logo { get; set; }
        public string Mission { get; set; }
        public string Vision { get; set; }
        public string CorporateValue { get; set; }
        public string Address { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Mail { get; set; }
        public string WorkHours { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string Instagram { get; set; }
        public string LinkedIn { get; set; }
        public string GoogleMaps { get; set; }
        public string HeadScripts { get; set; }
        public string FooterScripts { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
    }
}
